Prefix: ''
Homes:
  Enabled: true #Enable this module
  #The closest the player can be to 0,0
  Radius: 500
  #Message to send to the player when they are too close to spawn
  TooCloseMessage: '&3You must be at least&r&a 500&r&3 blocks from spawn'
  #Max homes a player can have
  MaxHomes: 3
RandomSpawn:
  Enabled: true #Enable this module
  #The max range to spawn the player
  Range: 500
  #World name to spawn the player in
  World: 'world'
  #Blocks to not spawn the player on
  Blocks:
    - 'STATIONARY_LAVA'
    - 'water'
    - 'lava'
    - 'air'
    - 'cactus'
TabList:
  Enabled: true #Enable this module
  Header:
    - ''
    - '&b&lL2X9'
    - '&r'
    - '&6i9 go brr'
    - ''
  Footer:
    - ''
    - '    &3%tps%&r&3 tps — %players% players — %ping% ping — %uptime% uptime    '
    - ''
    - '&7contact: l2x9.help@gmail.com'
    - '&7discussion: https://l2x9.ftp.sh/discord'
    - '&7website: https://l2x9.ftp.sh/'
    - '       &7These are the only official L2X9 websites and contacts       '
    - ''
Commands:
  Enabled: true #Enable this module
  #Help message
  HelpMessage:
    - "&6-----------------------------------------------------"
    - "&3/ignore <name> to ignore a player."
    - "&3/ignorelist to list ignored players."
    - "&3/r <message> to reply to the last person that messaged you."
    - "&3/l <message> to message the last person that you messaged."
    - "&3/w <name> <message> OR /msg <name> <message> to pm a player."
    - "&3/toggleconnectionmsgs to toggle join and leave messages."
    - "&3/togglechat to toggle the default chat."
    - "&3/toggledeathmsg to toggle all death messages."
    - "&3/kill to kill yourself."
    - "&3/stats to get world size and how many players have joined."
    - "&3/playtime to see a player's total playtime."
    - "&3/mostplaytime to show top playtimes."
    - "&3/discord to join the L2X9 discord."
    - "&6-----------------------------------------------------"

  #Message to send to the player for /discord
  Discord: '&3Join us on discord at&r&a https://discord.gg/8HNcbutwXW'
ChatControl:
  Enabled: true #Enable this module
  PreventLinks: true #Uses a list of all TLDs
  #How long before a player can chat again (In seconds)
  Cooldown: 3
  #Blocked words
  Blocked: []
Patches:
  CraftingLag:
    MaxVLS: 2000
    KickMessage: ''
