# !!! SEE THE LOCALIZATION CONFIG FILES FOR TABLIST CONFIGURATION !!!
#!!! SEE THE LOCALIZATION CONFIGS FOR HELP MESSAGE CONFIGURATION !!!

Prefix: ''
Homes:
  Enabled: true #Enable this module
  #The closest the player can be to 0,0
  Radius: 500
  #Message to send to the player when they are too close to spawn
  TooCloseMessage: '&3You must be at least&r&a 500&r&3 blocks from spawn'
  #Max homes a player can have
  MaxHomes: 3
RandomSpawn:
  Enabled: true #Enable this module
  #The max range to spawn the player
  Range: 500
  #World name to spawn the player in
  World: 'world'
  #Blocks to not spawn the player on
  Blocks:
    - 'STATIONARY_LAVA'
    - 'water'
    - 'lava'
    - 'air'
    - 'cactus'
Commands:
  Enabled: true #Enable this module
  #Help message
  # to send to the player for /discord
  Discord: '&3Join us on discord at&r&a https://discord.l2x9.me'
ChatControl:
  Enabled: true #Enable this module
  PreventLinks: true #Uses a list of all TLDs
  #How long before a player can chat again (In seconds)
  Cooldown: 3
  #Blocked words
  Blocked: []
  CommandWhitelist:
    - "/ignore"
    - "/unignore"
    - "/togglechat"
    - "/toggledeathmsg"
    - "/msg"
    - "/message"
    - "/whisper"
    - "/tell"
    - "/w"
    - "/reply"
    - "/r"
    - "/home"
    - "/sethome"
    - "/delhome"
    - "/help"
    - "/plugins"
    - "/pl"
    - "/kill"
    - "/stats"
    - "/discord"
Patches:
  FakePlugins:
    PluginList:
       'Hey idiot /pl is enabled'
Misc:
  EntityPerChunk:
    CheckInterval: 2 #In minutes
    EntitiesPerChunk:
      - 'wither::20'
      - 'armor_stand::15'
