BANNED_BLOCKS:
  - 'COMMAND_REPEATING'
  - 'GRASS_PATH'
  - 'KNOWLEDGE_BOOK'
  - 'STRUCTURE_VOID'
  - 'STRUCTURE_BLOCK'
  - 'BARRIER'
  - 'SOIL'
  - 'GRASS_PATH'
  - 'MOB_SPAWNER'
  - 'MONSTER_EGG'
  - 'MONSTER_EGGS'
  - 'ENDER_PORTAL_FRAME'
  - 'BEDROCK'
  - 'COMMAND'
  - 'COMMAND_MINECART'
  - 'COMMAND_CHAIN'