name: ${project.name}
version: ${project.version}
main: ${mainClass}
authors: [ 254n_m ]
description: All of the plugins for thr l2x9 reboot
commands:
  msg:
    aliases: [message, whisper, tell, w]
  reply:
    aliases: [r]