name: ${project.name}
version: ${project.version}
main: me.l2x9.core.L2X9RebootCore
authors: [ 254n_m ]
description: All of the plugins for thr l2x9 reboot
commands:
  msg:
    aliases: [message, whisper, tell, w, t]
  reply:
    aliases: [r]