Header:
  - ''
  - '&b&lL2X9'
  - '&r'
  - '&6i9 go brr'
  - ''
Footer:
  - ''
  - '    &3%tps%&r&3 tps — %players% players — %ping% ping — %uptime% uptime    '
  - ''
  - '&7contact: l2x9.help@gmail.com'
  - '&7discussion: https://l2x9.ftp.sh/discord'
  - '&7website: https://l2x9.ftp.sh/'
  - '       &7These are the only official L2X9 websites and contacts       '
  - ''